# Application
spring.application.name=${SPRING_APPLICATION_NAME}
spring.data.redis.repositories.enabled=false

server.port=${HOST_APP_PORT}
spring.mvc.favicon.enabled=false

# Docker
spring.docker.compose.enabled=false
spring.docker.compose.file=${SPRING_DOCKER_COMPOSE_FILE}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.datasource.driver-class-name=${DB_DRIVER}

# Security
spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

# Session & Redis
server.servlet.session.timeout=3600
spring.session.store-type=${SPRING_SESSION_STORE_TYPE}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
management.health.redis.enabled=true

# File Storage
uploadImageProfile.directory=${UPLOAD_IMAGE_PROFILE_DIRECTORY}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
